<?php

// VENGONO DICHIARATE NELLE PARENTESI DEL FOR 3 OPERAZIONI
// LA DICHIARAZIONE DELLA VARIABILE DI CICLO
// LA DICHIARAZIONE DELLA LUNGHEZZA DI CICLO
// LA DICHIARAZIONE DELLA MODALITA' DI SPOSTAMENTO NEL CICLO

//ESEMPIO COLLEGATO ALLA CAMMINATA
// PRIMO STEP - CREAZIONE PIEDE
// SECONDO STEP - DEFINIZIONE DISTANZA
// TERZO STEP - DEFINIZIONE LUNGHEZZA PASSO

echo 'nottefeffe';

for( $i=100 ; $i > 0 ; $i-- ){

    echo $i;

}

echo 'ciaofeffe';

?>

